[package]
name = "num-digits-micro-bench"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]

[dependencies]
itoa = { version = "0.4.1", features=["i128"] }

[dev-dependencies]
rand = "0.3.15"
